# Generated by Django 5.1.6 on 2025-03-19 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 5, 13, 34, 86764, tzinfo=datetime.timezone.utc)),
        ),
    ]
